spring:
  application:
    name: webhook

  datasource:
    url: jdbc:postgresql://localhost:5432/webhook_platform
    username: hp
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

security:
  webhook:
    encryption-key: ${WEBHOOK_ENCRYPTION_KEY}
